CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL
);

INSERT INTO items (title) VALUES ('ARRAY QUESTION'), ('STRING QUESTION') , ('LINKEDLIST QUESTION') , (' STACK QUESTION') , ('QUEUE QUESTION') , ('GRAPG QUESTION'), ('DP QUESTION');